version: '3.3'

services:
   messagebroker: 
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672" 
      - "5672:5672"   
  #  subscriber1:
  #   image: rabbittest/subscriber1:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: sub1-Dockerfile
    